#include "BasicMenuWidget.h"
#include "SettingsPanelWidget.h"
#include "Components/Button.h"
#include "Kismet/KismetSystemLibrary.h"

DEFINE_LOG_CATEGORY_STATIC(LogBasicMenu, Log, All);

void UBasicMenuWidget::NativeConstruct()
{
	Super::NativeConstruct();

	if (ResumeButton)
	{
		ResumeButton->OnClicked.AddDynamic(this, &UBasicMenuWidget::OnResumeClicked);
		UE_LOG(LogBasicMenu, Log, TEXT("âœ… Resume button bound"));
	}
	else
	{
		UE_LOG(LogBasicMenu, Error, TEXT("âŒ ResumeButton not found!"));
	}

	if (MultiplayerButton)
	{
		MultiplayerButton->OnClicked.AddDynamic(this, &UBasicMenuWidget::OnMultiplayerClicked);
		UE_LOG(LogBasicMenu, Log, TEXT("âœ… Multiplayer button bound"));
	}
	else
	{
		UE_LOG(LogBasicMenu, Error, TEXT("âŒ MultiplayerButton not found!"));
	}

	if (QuitButton)
	{
		QuitButton->OnClicked.AddDynamic(this, &UBasicMenuWidget::OnQuitClicked);
		UE_LOG(LogBasicMenu, Log, TEXT("âœ… Quit button bound"));
	}
	else
	{
		UE_LOG(LogBasicMenu, Error, TEXT("âŒ QuitButton not found!"));
	}
}

void UBasicMenuWidget::OnResumeClicked()
{
	UE_LOG(LogBasicMenu, Log, TEXT("â–¶ï¸ Resume clicked"));

	if (ParentPanel)
	{
		ParentPanel->HidePanel();
	}
}

void UBasicMenuWidget::OnMultiplayerClicked()
{
	UE_LOG(LogBasicMenu, Log, TEXT("ðŸŒ Multiplayer clicked"));

	if (ParentPanel)
	{
		ParentPanel->ShowMultiplayerMenu();
	}
}

void UBasicMenuWidget::OnQuitClicked()
{
	UE_LOG(LogBasicMenu, Log, TEXT("ðŸšª Quit clicked"));

	UKismetSystemLibrary::QuitGame(GetWorld(), nullptr, EQuitPreference::Quit, false);
}
